language: go

go:
  - "1.12"

env:
  - LDFLAGS="-s -w -X \"github.com/yhino/git-org/cmd/version.version=${TRAVIS_TAG}\" -X \"github.com/yhino/git-org/cmd/version.revision=`git rev-parse --short HEAD`\" -extldflags \"-static\""

before_install:
  - go get -u github.com/mitchellh/gox

install:
  - GO111MODULE=on go mod vendor

script:
  - go test -v ./...
  - GO111MODULE=on gox -os="linux darwin windows" -arch="amd64" -output="dist/git-org.{{.OS}}.{{.Arch}}" -ldflags="$LDFLAGS" -verbose ./...

deploy:
  provider: releases
  api_key: "$GITHUB_ACCESS_TOKEN"
  file_glob: true
  file: "dist/git-org.*"
  skip_cleanup: true
  on:
    tags: true
